name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            H9000_ger.tex
            H9000_eng.tex

      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path:       |
                H9000_ger.pdf
                H9000_eng.pdf
